// TOML workspace layout: capture, persist, and re-assert the shared mirror
// workspace's shape.
//
// This is the "a TOML that represents the workspace layout, saved and
// customizable across reboot" contract. The file (`layout.toml`, stored
// beside the per-host state, NOT beside hosts.toml — that file stays the host
// contract) is a hand-editable description of the fleet's local gang
// workspace: its label and its tabs in order, each tab listing its panes
// (which host a leaf mirrors; a hand-authored layout can also add split
// directions, following herdr-plus's `[[tabs.panes]]` vocabulary).
//
// What the file DOES and DOESN'T control, honestly:
//   - DOES: which workspace the mirrors share (label restamp), which tabs
//     exist in what order (native `tab.move`), and a readable leaf→host map.
//   - DOESN'T: intra-tab split geometry in the live arrangement. Converge
//     keeps the mirror tabs' topology faithful to the remote (layout_sync +
//     `layout.set_split_ratio`) and herdr cannot re-parent panes across tabs
//     after creation (`pane.move` returns SameTab), so `apply` re-orders and
//     never force-splits a live mirror. Split direction/ratio are captured
//     into the file for reference and future edits.
//
// Nothing here ever writes to a REMOTE herdr: the file shapes the local gang
// workspace only, so re-applying it can never rename a bot's workspaces.

use std::collections::HashMap;
use std::path::{Path, PathBuf};

use serde::{Deserialize, Serialize};
use serde_json::json;

use crate::api::ApiClient;
use crate::config::{load_config, MirrorConfig};
use crate::mirror::{fetch_snapshot, LayoutNode, Snapshot};
use crate::state::load_state;
use crate::util::{err, Env, Logger, Result};

const LAYOUT_FILE: &str = "layout.toml";
const DEFAULT_RATIO: f64 = 0.5;

fn default_ratio() -> f64 {
    DEFAULT_RATIO
}

// --- declarative model (round-trips through toml) ---

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LayoutFile {
    /// local shared-workspace label the layout describes
    pub workspace: String,
    /// tabs in order (first = index 0)
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub tabs: Vec<LayoutTab>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LayoutTab {
    /// tab label
    pub name: String,
    /// panes in this tab, in display order. The first has no `split`.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub panes: Vec<LayoutPane>,
}

#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct LayoutPane {
    /// which host this pane mirrors (absent = a plain local pane)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,
    /// the mirror's remote tab/workspace label (informational)
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tab: Option<String>,
    /// how this pane splits off the previous one: "right" | "down"
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub split: Option<String>,
    /// split ratio for `split` (0..1, best-effort capture / hand-editable)
    #[serde(default = "default_ratio")]
    pub ratio: f64,
}

// --- persistence ---

pub fn layout_path(state_dir: &Path) -> PathBuf {
    state_dir.join(LAYOUT_FILE)
}

pub fn load(state_dir: &Path) -> Result<Option<LayoutFile>> {
    let p = layout_path(state_dir);
    if !p.is_file() {
        return Ok(None);
    }
    let text = std::fs::read_to_string(&p).map_err(|e| err(format!("{}: {e}", p.display())))?;
    let file: LayoutFile = toml::from_str(&text).map_err(|e| err(format!("{}: {e}", p.display())))?;
    Ok(Some(file))
}

pub fn save(file: &LayoutFile, state_dir: &Path) -> Result<()> {
    std::fs::create_dir_all(state_dir)?;
    let body = toml::to_string_pretty(file)?;
    let header = format!(
        "# Mirror fleet workspace layout.\n\
         # Generated by `herdr-mirror layout save`; hand-editable.\n\
         # Re-asserted at daemon start and on `herdr-mirror layout apply`.\n\
         # Intra-tab split geometry stays LIVE (converge mirrors the remote);\n\
         # this file pins the workspace label, tab set, and tab order.\n\n"
    );
    std::fs::write(layout_path(state_dir), header + &body)?;
    Ok(())
}

// --- host/state resolution (which local object mirrors which remote) ---

/// local id → (host index, remote id), built from every host's state file.
struct Index {
    /// local pane id → (host index, remote pane id)
    panes: HashMap<String, (usize, String)>,
    /// local tab id → (host index, remote tab id)
    tabs: HashMap<String, (usize, String)>,
    /// local workspace id → (host index, remote workspace id)
    workspaces: HashMap<String, (usize, String)>,
    /// remote workspace id → last remote label (per host index)
    ws_labels: HashMap<(usize, String), Option<String>>,
    /// remote tab id → the remote workspace id it belongs to (per host index)
    tab_ws: HashMap<(usize, String), Option<String>>,
}

fn build_index(config: &MirrorConfig, state_dir: &Path) -> Index {
    let mut ix = Index {
        panes: HashMap::new(),
        tabs: HashMap::new(),
        workspaces: HashMap::new(),
        ws_labels: HashMap::new(),
        tab_ws: HashMap::new(),
    };
    for (hi, h) in config.hosts.iter().enumerate() {
        let st = load_state(state_dir, &h.name);
        for (rid, e) in &st.workspaces {
            ix.workspaces.insert(e.local_id.clone(), (hi, rid.clone()));
            ix.ws_labels.insert((hi, rid.clone()), e.last_remote_label.clone());
        }
        for (rid, e) in &st.tabs {
            ix.tabs.insert(e.local_id.clone(), (hi, rid.clone()));
            ix.tab_ws.insert((hi, rid.clone()), e.remote_workspace.clone());
        }
        for (rid, e) in &st.panes {
            ix.panes.insert(e.local_id.clone(), (hi, rid.clone()));
        }
    }
    ix
}

/// What the shared workspace's label SHOULD be: the first host's configured
/// `workspace` name, or (no shared mode) the default host's first mirror
/// workspace's label, or a last-ditch "Pantheon".
fn resolve_workspace_label(config: &MirrorConfig, snap: &Snapshot, state_dir: &Path) -> String {
    if let Some(ws) = config.hosts.iter().find_map(|h| h.workspace.clone()) {
        return ws;
    }
    let preferred = config.default_host();
    if let Some(host) = preferred {
        let st = load_state(state_dir, &host.name);
        if let Some(ws_id) = st.workspaces.values().find(|e| !e.is_tombstoned()).map(|e| e.local_id.clone()) {
            if let Some(lws) = snap.workspaces.iter().find(|w| w.workspace_id == ws_id) {
                return lws.label.clone();
            }
        }
    }
    "Pantheon".to_string()
}

// --- capture (live) ---

#[derive(Deserialize)]
struct Exported {
    layout: ExportedLayout,
}
#[derive(Deserialize)]
struct ExportedLayout {
    root: LayoutNode,
}

/// Per-leaf (pane id, split it diverges on — direction + ratio).
//
// Preorder DFS assigns each leaf the FIRST split that separates it from the
// previously visited leaf: the parent's edge for the first child, the current
// split's own edge for the second child (see tree_leaves). This reproduces
// the herdr-plus `[[tabs.panes]] split` vocabulary for any binary split tree.
fn tree_leaves(node: &LayoutNode, edge: Option<(String, f64)>, out: &mut Vec<(Option<String>, Option<(String, f64)>)>) {
    match node {
        LayoutNode::Pane { pane_id, .. } => out.push((pane_id.clone(), edge)),
        LayoutNode::Split { direction, ratio, first, second } => {
            tree_leaves(first, edge, out);
            tree_leaves(second, Some((direction.clone(), *ratio)), out);
        }
    }
}

/// Capture the configured shared workspace into a LayoutFile. Best-effort:
/// a tab whose template export fails keeps its flat pane list.
pub async fn capture(local: &ApiClient, state_dir: &Path, config: &MirrorConfig) -> Result<LayoutFile> {
    let snap = fetch_snapshot(local).await?;
    let label = resolve_workspace_label(config, &snap, state_dir);
    let ix = build_index(config, state_dir);
    let Some(lws) = snap.workspaces.iter().find(|w| w.label == label) else {
        // no live workspace yet — still a valid (empty) file: apply re-asserts
        // the label once converge creates it
        return Ok(LayoutFile { workspace: label, tabs: vec![] });
    };

    let mut tabs: Vec<LayoutTab> = Vec::new();
    let mut ws_tabs: Vec<_> = snap.tabs.iter().filter(|t| t.workspace_id == lws.workspace_id).collect();
    ws_tabs.sort_by_key(|t| t.number);
    for tab in ws_tabs {
        // host attribution: is this a mirror tab?
        let mirror_host = ix.tabs.get(&tab.tab_id).map(|(hi, _)| config.hosts[*hi].name.clone());
        // the tab's remote-workspace label, best-effort (informational)
        let remote_ws_label = ix
            .tabs
            .get(&tab.tab_id)
            .and_then(|(hi, rid)| ix.tab_ws.get(&(*hi, rid.clone())).cloned().flatten())
            .and_then(|rws| ix.ws_labels.get(&(ix.tabs[&tab.tab_id].0, rws)).cloned().flatten());

        let mut panes: Vec<LayoutPane> = Vec::new();
        let exported = local
            .request_t::<Exported>("layout.export", json!({ "tab_id": tab.tab_id }))
            .await;
        let mut leaves: Vec<(Option<String>, Option<(String, f64)>)> = Vec::new();
        match exported {
            Ok(e) => tree_leaves(&e.layout.root, None, &mut leaves),
            Err(_) => {
                // export failed (tab vanishing) — fall back to pane order
                let mut ps: Vec<_> = snap.panes.iter().filter(|p| p.tab_id == tab.tab_id).collect();
                ps.sort_by_key(|p| p.pane_id.clone());
                leaves = ps.iter().map(|p| (Some(p.pane_id.clone()), None)).collect();
            }
        }
        for (pane_id, split) in leaves {
            let host = pane_id
                .as_deref()
                .and_then(|pid| ix.panes.get(pid))
                .map(|(hi, _)| config.hosts[*hi].name.clone())
                .or_else(|| mirror_host.clone());
            panes.push(LayoutPane {
                tab: if host.is_some() { remote_ws_label.clone() } else { None },
                host,
                split: split.as_ref().map(|(d, _)| d.clone()),
                ratio: split.map(|(_, r)| r).unwrap_or(DEFAULT_RATIO),
            });
        }
        tabs.push(LayoutTab { name: tab.label.clone(), panes });
    }
    Ok(LayoutFile { workspace: label, tabs })
}

// --- apply (live, local-only, never destructive) ---

#[derive(Debug, PartialEq)]
struct OrderStep {
    tab_id: String,
    insert_index: usize,
}

/// Order-only plan: tab.move steps that put the live tabs into the declared
/// order. Declared labels with no live tab (host down) are skipped, so a
/// missing tab's slot is COMPACTED — a later declared tab fills it instead of
/// leaving a hole. Non-declared live tabs (a plain user tab in the shared
/// workspace) are left in place and drift to the end as the moves push them
/// right. Front-to-back, so each move is final: a tab moved to position i is
/// never moved again.
fn order_plan(live: &[(usize, String, String)], declared: &[String]) -> Vec<OrderStep> {
    let mut pos: HashMap<String, usize> = live.iter().map(|(n, id, _)| (id.clone(), *n)).collect();
    let mut used: std::collections::HashSet<String> = std::collections::HashSet::new();
    let mut target: Vec<String> = Vec::new();
    for name in declared {
        if let Some((_, id, _)) = live.iter().find(|(_, id, l)| l == name && !used.contains(id)) {
            used.insert(id.clone());
            target.push(id.clone());
        }
    }
    let mut steps: Vec<OrderStep> = Vec::new();
    for (i, id) in target.iter().enumerate() {
        let cur = pos[id];
        if cur != i {
            steps.push(OrderStep { tab_id: id.clone(), insert_index: i });
            // shift the [i, cur) range right; the moved tab lands at i
            for (_, p) in pos.iter_mut() {
                if *p >= i && *p < cur {
                    *p += 1;
                }
            }
            *pos.get_mut(id).unwrap() = i;
        }
    }
    steps
}

/// Re-assert the saved layout onto the LIVE shared workspace: restamp the
/// label (local only) and reorder the tabs to the declared order via native
/// `tab.move`. Never creates panes — converge is the single creator of mirror
/// content — and never touches a remote.
pub async fn apply(local: &ApiClient, state_dir: &Path, log: &Logger) -> Result<()> {
    let Some(file) = load(state_dir)? else {
        return Ok(());
    };
    let path = layout_path(state_dir);
    let snap = fetch_snapshot(local).await?;

    let live_ws = snap
        .workspaces
        .iter()
        .find(|w| w.label == file.workspace)
        .or_else(|| snap.workspaces.iter().find(|w| w.label.eq_ignore_ascii_case(&file.workspace)));
    let Some(lws) = live_ws else {
        log.log(&format!("layout apply: workspace {:?} not live yet (converging will create it)", file.workspace));
        return Ok(());
    };
    if lws.label != file.workspace {
        log.log(&format!(
            "layout apply: restamping local workspace {} → {:?}",
            lws.label, file.workspace
        ));
        local
            .request("workspace.rename", json!({ "workspace_id": lws.workspace_id, "label": file.workspace }))
            .await?;
    }

    let mut live_tabs: Vec<(usize, String, String)> = snap
        .tabs
        .iter()
        .filter(|t| t.workspace_id == lws.workspace_id)
        .map(|t| (t.number, t.tab_id.clone(), t.label.clone()))
        .collect();
    live_tabs.sort_by_key(|(num, _, _)| *num);
    let declared: Vec<String> = file.tabs.iter().map(|t| t.name.clone()).collect();
    let steps = order_plan(&live_tabs, &declared);
    let mut moved = 0usize;
    for step in steps {
        log.log(&format!(
            "layout apply: {} → position {}",
            step.tab_id,
            step.insert_index
        ));
        if let Err(e) = local
            .request("tab.move", json!({ "tab_id": step.tab_id, "insert_index": step.insert_index }))
            .await
        {
            log.log(&format!("layout apply: tab.move failed ({e})"));
            continue;
        }
        moved += 1;
    }
    let live_names: Vec<String> = live_tabs.iter().map(|(_, _, l)| l.clone()).collect();
    log.log(&format!(
        "layout apply: workspace {:?}, {} declared tabs, {} reordered, {}/{} live",
        file.workspace,
        declared.len(),
        moved,
        live_names.len(),
        declared.len()
    ));
    log.log(&format!("layout file: {}", path.display()));
    Ok(())
}

/// Boot-time restore inside the daemon: no-op when no layout file exists.
pub async fn apply_if_present(local: &ApiClient, env: &Env, log: &Logger) -> Result<()> {
    if load(&env.state_dir)?.is_none() {
        return Ok(());
    }
    apply(local, &env.state_dir, log).await
}

// --- CLI ---

/// Wait a beat for the first converges to map the mirrors before applying the
/// saved order (a fresh daemon with no layout is a no-op). Runs once, exits.
pub fn spark_apply(env: Env, log: Logger) -> tokio::task::JoinHandle<()> {
    tokio::spawn(async move {
        tokio::time::sleep(std::time::Duration::from_secs(10)).await;
        let result = match ApiClient::connect(&env.local_socket).await {
            Ok(local) => apply_if_present(&local, &env, &log).await,
            Err(e) => Err(e),
        };
        match result {
            Ok(()) => log.log("layout apply (boot) complete"),
            Err(e) => log.log(&format!("layout apply (boot) failed: {e}")),
        }
    })
}

pub fn cmd(env: &Env, rest: &[String]) -> Result<()> {
    let sub = rest.first().map(String::as_str).unwrap_or("status");
    match sub {
        "export" | "save" => {
            let rt = tokio::runtime::Builder::new_current_thread().enable_all().build()?;
            rt.block_on(async {
                let config = load_config(&env.config_search)?;
                let local = ApiClient::connect(&env.local_socket).await?;
                let file = capture(&local, &env.state_dir, &config).await?;
                if sub == "save" {
                    save(&file, &env.state_dir)?;
                    println!("saved layout to {}", layout_path(&env.state_dir).display());
                    println!("{} tabs under workspace {:?}", file.tabs.len(), file.workspace);
                } else {
                    println!("{}", toml::to_string_pretty(&file)?);
                }
                Ok(())
            })
        }
        "apply" => {
            let rt = tokio::runtime::Builder::new_current_thread().enable_all().build()?;
            rt.block_on(async {
                let local = ApiClient::connect(&env.local_socket).await?;
                let log = Logger::new(&env.state_dir, true);
                apply(&local, &env.state_dir, &log).await
            })
        }
        "status" => {
            let rt = tokio::runtime::Builder::new_current_thread().enable_all().build()?;
            rt.block_on(async {
                let config = load_config(&env.config_search)?;
                let local = ApiClient::connect(&env.local_socket).await?;
                let snap = fetch_snapshot(&local).await?;
                let label = resolve_workspace_label(&config, &snap, &env.state_dir);
                match load(&env.state_dir)? {
                    None => println!(
                        "layout: none at {} (run `herdr-mirror layout save` ",
                        layout_path(&env.state_dir).display()
                    ),
                    Some(file) => {
                        let live = snap.workspaces.iter().filter(|w| w.label == file.workspace).count();
                        let live_tabs = snap
                            .tabs
                            .iter()
                            .filter(|t| snap.workspaces.iter().any(|w| w.workspace_id == t.workspace_id && w.label == file.workspace))
                            .count();
                        println!("layout: {} ({}/1 live workspace, {} tabs declared)", layout_path(&env.state_dir).display(), live, file.tabs.len());
                        println!("  workspace \"{}\" (live label on this host: {} — capture label {})", file.workspace, label, label);
                        println!("  tabs declared: {}", file.tabs.len());
                        println!("  live mirror tabs in workspace: {live_tabs}");
                        for (i, t) in file.tabs.iter().enumerate() {
                            let hosts: Vec<&str> = t.panes.iter().filter_map(|p| p.host.as_deref()).collect();
                            let who = if hosts.is_empty() { String::from("local panes") } else { hosts.join(", ") };
                            println!("    {:>2}) {} — {}", i, t.name, who);
                        }
                    }
                }
                Ok(())
            })
        }
        "path" => {
            println!("{}", layout_path(&env.state_dir).display());
            Ok(())
        }
        other => Err(err(format!(
            "layout: unknown subcommand {other:?} (export|save|apply|status|path)"
        ))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn pane(id: Option<&str>) -> LayoutNode {
        LayoutNode::Pane { pane_id: id.map(|s| s.to_string()), label: None }
    }
    fn split(dir: &str, ratio: f64, first: LayoutNode, second: LayoutNode) -> LayoutNode {
        LayoutNode::Split {
            direction: dir.to_string(),
            ratio,
            first: Box::new(first),
            second: Box::new(second),
        }
    }

    #[test]
    fn layout_toml_roundtrips() {
        let file = LayoutFile {
            workspace: "Pantheon".into(),
            tabs: vec![
                LayoutTab {
                    name: "Heimdall".into(),
                    panes: vec![LayoutPane {
                        host: Some("heimdall".into()),
                        tab: Some("main".into()),
                        split: None,
                        ratio: 0.5,
                    }],
                },
                LayoutTab {
                    name: "Ops".into(),
                    panes: vec![
                        LayoutPane { host: Some("eir".into()), tab: None, split: None, ratio: 0.5 },
                        LayoutPane {
                            host: Some("sindri".into()),
                            tab: None,
                            split: Some("right".into()),
                            ratio: 0.62,
                        },
                    ],
                },
            ],
        };
        let text = toml::to_string_pretty(&file).unwrap();
        let back: LayoutFile = toml::from_str(&text).unwrap();
        assert_eq!(back, file);
        assert!(text.contains("workspace = \"Pantheon\""));
    }

    /// Persistence across reboot: save() writes the file load() reads — the
    /// exact mechanism a daemon restart (or `layout apply`) uses to recover a
    /// hand-curated arrangement. What survives is byte-equivalent, not just
    /// field-equal.
    #[test]
    fn saved_layout_survives_a_disk_round_trip() {
        let dir = std::env::temp_dir().join(format!("herdr-mirror-layout-{}", std::process::id()));
        let _ = std::fs::remove_dir_all(&dir);
        let file = LayoutFile {
            workspace: "Pantheon".into(),
            tabs: vec![
                LayoutTab {
                    name: "Urd".into(),
                    panes: vec![LayoutPane {
                        host: Some("urd".into()),
                        tab: Some("urd".into()),
                        split: None,
                        ratio: 0.5,
                    }],
                },
                LayoutTab {
                    name: "Ops".into(),
                    panes: vec![
                        LayoutPane { host: Some("eir".into()), tab: None, split: None, ratio: 0.5 },
                        LayoutPane {
                            host: Some("sindri".into()),
                            tab: None,
                            split: Some("right".into()),
                            ratio: 0.4,
                        },
                    ],
                },
            ],
        };
        save(&file, &dir).unwrap();
        let back = load(&dir).unwrap().expect("layout.toml must exist after save");
        assert_eq!(back, file);
        // the header comment is preserved and the file is genuinely on disk
        let raw = std::fs::read_to_string(layout_path(&dir)).unwrap();
        assert!(raw.starts_with("# Mirror fleet workspace layout."));
        // a second load (simulated daemon restart) sees the identical file
        assert_eq!(load(&dir).unwrap(), Some(file));
        let _ = std::fs::remove_dir_all(&dir);
    }

    /// A single-pane tab has no split on its only leaf.
    #[test]
    fn tree_leaves_single_pane() {
        let tree = pane(Some("w:p1"));
        let mut out = Vec::new();
        tree_leaves(&tree, None, &mut out);
        assert_eq!(out.len(), 1);
        assert_eq!(out[0].0.as_deref(), Some("w:p1"));
        assert!(out[0].1.is_none());
    }

    /// Two panes side by side: second leaf carries the split.
    #[test]
    fn tree_leaves_two_way_split() {
        let tree = split("right", 0.6, pane(Some("a")), pane(Some("b")));
        let mut out = Vec::new();
        tree_leaves(&tree, None, &mut out);
        assert_eq!(out[0].1, None);
        assert_eq!(out[1].1, Some(("right".to_string(), 0.6)));
    }

    /// Nested splits: each leaf gets the FIRST split that separates it from
    /// the previous leaf (preorder), which is what a flat pane list with
    /// `split` entries must mean.
    #[test]
    fn tree_leaves_nested_split() {
        // root right(a, inner down(a1, a2)) → a, a1, a2
        let tree = split("right", 0.5, pane(Some("a")), split("down", 0.4, pane(Some("a1")), pane(Some("a2"))));
        let mut out = Vec::new();
        tree_leaves(&tree, None, &mut out);
        assert_eq!(
            out.iter().map(|(id, _)| id.clone().unwrap()).collect::<Vec<_>>(),
            vec!["a".to_string(), "a1".to_string(), "a2".to_string()]
        );
        assert_eq!(out[0].1, None);
        assert_eq!(out[1].1, Some(("right".to_string(), 0.5))); // a1 leaves a at the root
        assert_eq!(out[2].1, Some(("down".to_string(), 0.4))); // a2 leaves a1 at the inner split
    }

    /// Trivial: declared order already matches live → one step per tab
    /// (a move to its own position is dropped by apply, but the plan lists a
    /// step only when the position actually differs).
    #[test]
    fn order_plan_in_order_is_noop() {
        let live = vec![(0, "t0".into(), "A".into()), (1, "t1".into(), "B".into())];
        let declared = vec!["A".to_string(), "B".to_string()];
        assert!(order_plan(&live, &declared).is_empty());
    }

    /// Declared order differs → move C (the only displaced tab) to the front;
    /// A and B fall into place as C's move shifts them right. One move, not
    /// three: the plan must not re-move a tab a front-move already lands.
    #[test]
    fn order_plan_reorders() {
        let live = vec![(0, "t0".into(), "A".into()), (1, "t1".into(), "B".into()), (2, "t2".into(), "C".into())];
        let declared = vec!["C".to_string(), "A".to_string(), "B".to_string()];
        let steps = order_plan(&live, &declared);
        assert_eq!(steps.len(), 1);
        assert_eq!(steps[0], OrderStep { tab_id: "t2".into(), insert_index: 0 });
    }

    /// A declared tab with no live match (host down) is skipped and its slot
    /// COMPACTS: the surviving tabs already sit in the compacted order, so no
    /// moves are needed.
    #[test]
    fn order_plan_missing_label_compacts() {
        let live = vec![(0, "t0".into(), "A".into()), (1, "t1".into(), "C".into())];
        let declared = vec!["A".to_string(), "B".to_string(), "C".to_string()]; // B down
        assert!(order_plan(&live, &declared).is_empty());
    }

    /// A non-declared tab sitting ahead of the declared set is pushed out of
    /// the way: the declared tab moves into its own slot, not behind it.
    #[test]
    fn order_plan_extra_tab_gets_pushed() {
        let live = vec![(0, "x0".into(), "X".into()), (1, "t1".into(), "B".into())];
        let declared = vec!["B".to_string()];
        let steps = order_plan(&live, &declared);
        assert_eq!(steps.len(), 1);
        assert_eq!(steps[0], OrderStep { tab_id: "t1".into(), insert_index: 0 });
    }

    /// A declared tab that's already at its spot isn't moved a second time
    /// even when an earlier slot is 'filled' by a non-declared live tab.
    #[test]
    fn order_plan_never_double_moves() {
        let live = vec![(0, "extra".into(), "X".into()), (1, "t1".into(), "B".into())];
        let declared = vec!["B".to_string()];
        let steps = order_plan(&live, &declared);
        // B is at position 1 in the live list, declared position 0 → move
        assert_eq!(steps.len(), 1);
        assert_eq!(steps[0], OrderStep { tab_id: "t1".into(), insert_index: 0 });
    }

    /// Shared mode: a host's `workspace` names the layout's workspace.
    #[test]
    fn workspace_label_from_config() {
        let cfg = MirrorConfig {
            poll_seconds: 60,
            autostart: false,
            default_host: Some("a".into()),
            close_remote_on_local_close: true,
            viewer_labels: true,
            hosts: vec![
                crate::config::HostConfig {
                    name: "a".into(),
                    target: "a.mesh".into(),
                    kind: crate::config::HostKind::Ssh,
                    docker_bin: String::new(),
                    prefix: "A".into(),
                    label: "A".into(),
                    remote_bin: None,
                    session: None,
                    api_transport: crate::config::ApiTransport::Auto,
                    always_control: true,
                    max_cols: None,
                    max_rows: None,
                    workspace: Some("Pantheon".into()),
                },
            ],
            source: None,
            shadowed: vec![],
            warnings: vec![],
        };
        let snap = Snapshot { workspaces: vec![], tabs: vec![], panes: vec![], agents: vec![], layouts: vec![] };
        assert_eq!(resolve_workspace_label(&cfg, &snap, Path::new("/tmp")), "Pantheon");
    }

    /// The tree decomposition round-trips through the TOML vocabulary: what
    /// tree_leaves emits is exactly what a hand-authored [[tab.panes]] list
    /// would say for the same tree.
    #[test]
    fn tree_leaves_matches_toml_pane_list() {
        let tree = split("down", 0.5, pane(Some("x")), split("right", 0.3, pane(Some("y")), pane(Some("z"))));
        let mut out = Vec::new();
        tree_leaves(&tree, None, &mut out);
        let x: Vec<Option<(String, f64)>> = out.iter().map(|(_, s)| s.clone()).collect();
        assert_eq!(x[0], None);
        assert_eq!(x[1], Some(("down".to_string(), 0.5)));
        assert_eq!(x[2], Some(("right".to_string(), 0.3)));
    }
}